### ISSUE TITLE
Installing plugin is causing max player count be calculated wrong

### ISSUE THREAD

**Issue by realmbmc** [storm37000/SCPSL_Smod_ServerNameVars#1]
smod thinks that max player count is not 20 but 20 + 10 reserved slots so it outputs 30

**Comment by storm37000** [comment]
if that is a bug in smod then i can make my own method of obtaining the info.

**Comment by realmbmc** [comment]
No, it happens only if I install your plugin

**Comment by storm37000** [comment]
well it overrides the vanilla smod vars because they werent working at all at the time, it is getting the data from vanilla smod, you can comment out the line with the player count with // and recompile.
