### ISSUE TITLE
name issues

### ISSUE THREAD

**Issue by sxnfulv2** [storm37000/SCPSL_Smod_ServerNameVars#2]
I try displaying the amount of Classds, scps, mtf and if the warhead is detonated on my server name.
It just shows up as zeroes, especially the warhead one
![capture](https://user-images.githubusercontent.com/44823661/48104226-5e43d980-e1e7-11e8-954a-fdc98fe4b671.PNG)

**Comment by storm37000** [comment]
did you put them in the sm_server_name config option, not the vanilla server_name.
